### PR TITLE
 Adding type definitions for Typescript

### PR DESCRIPTION
**Pull request by danilofuchs**
Types generated based on documentation, propTypes and real-case usage.
Has been tested and refined. Some types are unclear to define, so they are noted as "any"

### CODE REVIEW

**Comment by ptcampbell** [comment]
Thanks for this @danilofuchs!

Could we get eyes on this @Secretmapper?

**Comment by Secretmapper** [comment]
Thanks for the PR!

**Comment by rnmp** [comment]
Thanks @danilofuchs for writing the types. Now, are we all aware that these don't make it to the final build? My only solution atm is to just copy/paste what @danilofuchs created into a custom file?

**Comment by danilofuchs** [comment]
@rnmp I think I forgot to add [src/types/index.d.ts](https://github.com/Secretmapper/react-image-annotation/blob/master/src/types/index.d.ts) into the published `files` array. I am currently not developing for this library as much as when I initially did this work, so it may be outdated.

**Comment by rnmp** [comment]
@danilofuchs yeah, I figured. That's okay though, I had created some of my own so it was easier to just copy/paste what you had and expand from there!

**Pull request merged**
