### PR TITLE
Abort point annotation when description is empty. Fix #7

### LINKED ISSUE #7: Click to Abort PointSelector Annotation
When I am using the PointSelector and I click outside of the currently open editor window I get the following error in the logs:

```
onClick of selector type POINT returned undefined.
Make sure to explicitly return the previous state
```

The expected behavior is that the annotation should be aborted/deleted the same way that the Rectangle/Oval selectors do.

### PR DESCRIPTION
**Pull request by joshuadeguzman**

### CODE REVIEW

**Comment by HunterFortuin** [comment]
This looks great to me. Thanks so much @joshuadeguzman!

**Comment by Secretmapper** [comment]
Thanks for the PR @joshuadeguzman!

**Comment by joshuadeguzman** [comment]
Cheers @Secretmapper!

**Comment by ptcampbell** [comment]
@joshuadeguzman this didn't seem to work for me — I still get the same error reported in #7 

It also doesn't seem to work on the demo page.

**Pull request merged**
