### PR TITLE
Support for update/edit or delete of annotations

### PR DESCRIPTION
**Pull request by stevehawley**
Addresses issue #14

### CODE REVIEW

**Comment by VitaliyKotov** [comment]
@stevehawley Hi, when this PR is supposed to be merged?

**Comment by stevehawley** [comment]
Hi @VitaliyKotov, that would be up to the maintainer

**Comment by danilofuchs** [comment]
@Secretmapper please take a look

**Comment by Secretmapper** [comment]
Hi! Thaks for the PR!

This functionality is already possible with Custom Content - namely, `renderContent` can have the buttons for delete/submit, and also be an editor, similar to the threaded comments example.

I think keeping the core package lean is best as this can be done in userspace, however, it might be a good idea to have an example (and also make it easier to write custom content). I made an issue #36 tracking it so I can add it in the future (PRs welcome as well)

**Pull request closed without merging**
